[workspace]
resolver = "2"

members = [
    "common",
    "server",
    "agent"
]

[dependencies]
common = { path = "../common" } # On importe notre propre lib
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"